"""-m

Revision ID: 91a64254f49c
Revises: 
Create Date: 2022-06-29 13:05:28.497737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91a64254f49c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_icon', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Enum('active', 'inactive', name='ck_category_states', native_enum=False, create_constraint=True, length=255), server_default='active', nullable=False),
    sa.Column('status', sa.Enum('inactive', 'active', name='ck_category_statuses', native_enum=False, create_constraint=True, length=255), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_table('subcategories',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subcategory_icon', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Enum('inactive', 'active', name='ck_subcategory_states', native_enum=False, create_constraint=True, length=255), server_default='active', nullable=False),
    sa.Column('status', sa.Enum('inactive', 'active', name='ck_subcategory_statuses', native_enum=False, create_constraint=True, length=255), server_default='active', nullable=False),
    sa.Column('category_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_subcategories_category_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subcategories'))
    )
    op.create_index(op.f('ix_subcategories_category_id'), 'subcategories', ['category_id'], unique=False)
    op.create_table('items',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('state', sa.Enum('active', 'inactive', name='ck_items_states', native_enum=False, create_constraint=True, length=255), server_default='active', nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='ck_items_status', native_enum=False, create_constraint=True, length=255), server_default='active', nullable=False),
    sa.Column('subcategory_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('category_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_items_category_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], name=op.f('fk_items_subcategory_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items'))
    )
    op.create_index(op.f('ix_items_category_id'), 'items', ['category_id'], unique=False)
    op.create_index(op.f('ix_items_subcategory_id'), 'items', ['subcategory_id'], unique=False)
    op.create_table('galleries',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('main_photo', sa.String(length=255), nullable=False),
    sa.Column('items_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['items_id'], ['items.id'], name=op.f('fk_galleries_items_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_galleries'))
    )
    op.create_index(op.f('ix_galleries_items_id'), 'galleries', ['items_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_galleries_items_id'), table_name='galleries')
    op.drop_table('galleries')
    op.drop_index(op.f('ix_items_subcategory_id'), table_name='items')
    op.drop_index(op.f('ix_items_category_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_subcategories_category_id'), table_name='subcategories')
    op.drop_table('subcategories')
    op.drop_table('categories')
    # ### end Alembic commands ###
