"""-m

Revision ID: e562a49899a0
Revises: 6ace83f4205a
Create Date: 2022-07-11 09:24:56.856086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e562a49899a0'
down_revision = '6ace83f4205a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('galleries', sa.Column('path', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('galleries', 'path')
    # ### end Alembic commands ###
